lsa_phd/config/routes.rb
Lsa::Application.routes.draw do

  resources :lsa_training_unique_words


  resources :flsa_results


  resources :lsa_test_words


  resources :lsa_test_sentences


  resources :lsa_words
  resources :lsa_sentences
  resources :lsa_documents
  resources :words
  resources :sentences
  resources :documents
  root to: 'documents#index'
  match ':controller(/:action(/:id))(.:format)'
end

lsa_phd/app/models/lsa_sentence.rb
class LsaSentence < ActiveRecord::Base
  attr_accessible :lsa_document_id, :sentence, :document_id
  has_many	:lsa_words, :dependent => :delete_all
  belongs_to :lsa_document
  belongs_to :document
end

lsa_phd/app/controllers/lsa_sentences_controller.rb
class LsaSentencesController < ApplicationController
  # GET /lsa_sentences
  # GET /lsa_sentences.json
  def index
    @lsa_sentences = LsaSentence.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lsa_sentences }
    end
  end

  # GET /lsa_sentences/1
  # GET /lsa_sentences/1.json
  def show
    @lsa_sentence = LsaSentence.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lsa_sentence }
    end
  end

  # GET /lsa_sentences/new
  # GET /lsa_sentences/new.json
  def new
    @lsa_sentence = LsaSentence.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lsa_sentence }
    end
  end

  # GET /lsa_sentences/1/edit
  def edit
    @lsa_sentence = LsaSentence.find(params[:id])
  end

  # POST /lsa_sentences
  # POST /lsa_sentences.json
  def create
    @lsa_sentence = LsaSentence.new(params[:lsa_sentence])

    respond_to do |format|
      if @lsa_sentence.save
        format.html { redirect_to @lsa_sentence, notice: 'Lsa sentence was successfully created.' }
        format.json { render json: @lsa_sentence, status: :created, location: @lsa_sentence }
      else
        format.html { render action: "new" }
        format.json { render json: @lsa_sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lsa_sentences/1
  # PUT /lsa_sentences/1.json
  def update
    @lsa_sentence = LsaSentence.find(params[:id])

    respond_to do |format|
      if @lsa_sentence.update_attributes(params[:lsa_sentence])
        format.html { redirect_to @lsa_sentence, notice: 'Lsa sentence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lsa_sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lsa_sentences/1
  # DELETE /lsa_sentences/1.json
  def destroy
    @lsa_sentence = LsaSentence.find(params[:id])
    @lsa_sentence.destroy

    respond_to do |format|
      format.html { redirect_to lsa_sentences_url }
      format.json { head :no_content }
    end
  end
end

lsa_phd/app/helpers/lsa_sentences_helper.rb
module LsaSentencesHelper
end

lsa_phd/app/views/lsa_sentences/_form.html.erb
<%= form_for(@lsa_sentence) do |f| %>
  <% if @lsa_sentence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lsa_sentence.errors.count, "error") %> prohibited this lsa_sentence from being saved:</h2>

      <ul>
      <% @lsa_sentence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sentence %><br />
    <%= f.text_area :sentence, :size => "120x25" %>
  </div>
  <div class="field">
    <%= f.label :lsa_document_id %><br />
    <%= f.number_field :lsa_document_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lsa_phd/app/views/lsa_sentences/edit.html.erb
<h1>Editing lsa_sentence</h1>

<%= render 'form' %>

<%= link_to 'Show', @lsa_sentence %> |
<%= link_to 'Back', lsa_sentences_path %>

lsa_phd/app/views/lsa_sentences/index.html.erb
<h1>Listing lsa_sentences</h1>

<table>
  <tr>
    <th>Sentence</th>
    <th>Lsa document</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lsa_sentences.each do |lsa_sentence| %>
  <tr>
    <td><%= lsa_sentence.sentence %></td>
    <td><%= lsa_sentence.lsa_document_id %></td>
    <td><%= link_to 'Show', lsa_sentence %></td>
    <td><%= link_to 'Edit', edit_lsa_sentence_path(lsa_sentence) %></td>
    <td><%= link_to 'Destroy', lsa_sentence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lsa sentence', new_lsa_sentence_path %>

lsa_phd/app/views/lsa_sentences/new.html.erb
<h1>New lsa_sentence</h1>

<%= render 'form' %>

<%= link_to 'Back', lsa_sentences_path %>

lsa_phd/app/views/lsa_sentences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sentence:</b>
  <%= @lsa_sentence.sentence %>
</p>

<p>
  <b>Lsa document:</b>
  <%= @lsa_sentence.lsa_document_id %>
</p>

<%= link_to 'Edit', edit_lsa_sentence_path(@lsa_sentence) %> |
<%= link_to 'Back', lsa_sentences_path %>