lsa_phd/config/routes.rb
Lsa::Application.routes.draw do

  resources :lsa_training_unique_words


  resources :flsa_results


  resources :lsa_test_words


  resources :lsa_test_sentences


  resources :lsa_words
  resources :lsa_sentences
  resources :lsa_documents
  resources :words
  resources :sentences
  resources :documents
  root to: 'documents#index'
  match ':controller(/:action(/:id))(.:format)'
end

lsa_phd/app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :content, :title, :label, :docno, :date
  has_many	:sentences, :dependent => :delete_all
  has_many	:words, :dependent => :delete_all
  has_many	:lsa_sentences, :dependent => :delete_all
  has_many	:lsa_test_sentences, :dependent => :delete_all
  has_many	:flsa_results, :dependent => :delete_all
end

lsa_phd/app/models/flsa_result.rb
class FlsaResult < ActiveRecord::Base
  attr_accessible :document_id, :f_measure, :flsa_label, :flsa_max_similarity, :label, :lsa_document_id, :lsa_label, :lsa_max_similarity, :precision, :recall
  belongs_to :lsa_document
  belongs_to :document
end

lsa_phd/app/models/lsa_document.rb
class LsaDocument < ActiveRecord::Base
  attr_accessible :title, :matrix, :testing, :training
  has_many	:lsa_sentences, :dependent => :delete_all
  has_many	:lsa_test_sentences, :dependent => :delete_all
  has_many	:lsa_words, :dependent => :delete_all
  has_many	:lsa_test_words, :dependent => :delete_all
  has_many	:flsa_results, :dependent => :delete_all
  has_many	:lsa_training_unique_words, :dependent => :delete_all
end

lsa_phd/app/models/lsa_sentence.rb
class LsaSentence < ActiveRecord::Base
  attr_accessible :lsa_document_id, :sentence, :document_id
  has_many	:lsa_words, :dependent => :delete_all
  belongs_to :lsa_document
  belongs_to :document
end

lsa_phd/app/models/lsa_test_sentence.rb
class LsaTestSentence < ActiveRecord::Base
  attr_accessible :document_id, :f_measure, :label, :lsa_document_id, :lsa_label, :precision, :recall, :sentence, :similarity
  has_many	:lsa_test_words, :dependent => :delete_all
  belongs_to :lsa_document
  belongs_to :document
end

lsa_phd/app/models/lsa_test_word.rb
class LsaTestWord < ActiveRecord::Base
  attr_accessible :lsa_document_id, :lsa_test_sentence_id, :word
  belongs_to	:lsa_test_sentence
  belongs_to	:lsa_document
end

lsa_phd/app/models/lsa_training_unique_word.rb
class LsaTrainingUniqueWord < ActiveRecord::Base
  attr_accessible :category_frequency, :icf, :lsa_document_id, :word, :occurrence
  belongs_to :lsa_document
end

lsa_phd/app/models/lsa_word.rb
class LsaWord < ActiveRecord::Base
  attr_accessible :lsa_document_id, :lsa_sentence_id, :word
  belongs_to	:lsa_sentence
  belongs_to	:lsa_document
end

lsa_phd/app/models/sentence.rb
class Sentence < ActiveRecord::Base
  attr_accessible :document_id, :sentence
  has_many	:words, :dependent => :delete_all
  belongs_to :document
end

lsa_phd/app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :document_id, :sentence_id, :word, :corpus
  belongs_to	:sentence
  belongs_to	:document
end

lsa_phd/app/controllers/lsa_training_unique_words_controller.rb
class LsaTrainingUniqueWordsController < ApplicationController
  # GET /lsa_training_unique_words
  # GET /lsa_training_unique_words.json
  def index
    @lsa_training_unique_words = LsaTrainingUniqueWord.find_all_by_lsa_document_id(params[:lsa_document_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lsa_training_unique_words }
    end
  end

  # GET /lsa_training_unique_words/1
  # GET /lsa_training_unique_words/1.json
  def show
    @lsa_training_unique_word = LsaTrainingUniqueWord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lsa_training_unique_word }
    end
  end

  # GET /lsa_training_unique_words/new
  # GET /lsa_training_unique_words/new.json
  def new
    @lsa_training_unique_word = LsaTrainingUniqueWord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lsa_training_unique_word }
    end
  end

  # GET /lsa_training_unique_words/1/edit
  def edit
    @lsa_training_unique_word = LsaTrainingUniqueWord.find(params[:id])
  end

  # POST /lsa_training_unique_words
  # POST /lsa_training_unique_words.json
  def create
    @lsa_training_unique_word = LsaTrainingUniqueWord.new(params[:lsa_training_unique_word])

    respond_to do |format|
      if @lsa_training_unique_word.save
        format.html { redirect_to @lsa_training_unique_word, notice: 'Lsa training unique word was successfully created.' }
        format.json { render json: @lsa_training_unique_word, status: :created, location: @lsa_training_unique_word }
      else
        format.html { render action: "new" }
        format.json { render json: @lsa_training_unique_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lsa_training_unique_words/1
  # PUT /lsa_training_unique_words/1.json
  def update
    @lsa_training_unique_word = LsaTrainingUniqueWord.find(params[:id])

    respond_to do |format|
      if @lsa_training_unique_word.update_attributes(params[:lsa_training_unique_word])
        format.html { redirect_to @lsa_training_unique_word, notice: 'Lsa training unique word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lsa_training_unique_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lsa_training_unique_words/1
  # DELETE /lsa_training_unique_words/1.json
  def destroy
    @lsa_training_unique_word = LsaTrainingUniqueWord.find(params[:id])
    @lsa_training_unique_word.destroy

    respond_to do |format|
      format.html { redirect_to lsa_training_unique_words_url }
      format.json { head :no_content }
    end
  end
end

lsa_phd/app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.json
  def index
    @words = Word.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/new
  # GET /words/new.json
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to words_url, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
end

lsa_phd/app/helpers/application_helper.rb
module ApplicationHelper
end

lsa_phd/app/helpers/documents_helper.rb
module DocumentsHelper
end

lsa_phd/app/helpers/flsa_results_helper.rb
module FlsaResultsHelper
end

lsa_phd/app/helpers/lsa_documents_helper.rb
module LsaDocumentsHelper
end

lsa_phd/app/helpers/lsa_sentences_helper.rb
module LsaSentencesHelper
end

lsa_phd/app/helpers/lsa_test_words_helper.rb
module LsaTestWordsHelper
end

lsa_phd/app/helpers/lsa_training_unique_words_helper.rb
module LsaTrainingUniqueWordsHelper
end

lsa_phd/app/helpers/lsa_words_helper.rb
module LsaWordsHelper
end

lsa_phd/app/helpers/sentences_helper.rb
module SentencesHelper
end

lsa_phd/app/helpers/words_helper.rb
module WordsHelper
end

lsa_phd/app/views/lsa_training_unique_words/_form.html.erb
<%= form_for(@lsa_training_unique_word) do |f| %>
  <% if @lsa_training_unique_word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lsa_training_unique_word.errors.count, "error") %> prohibited this lsa_training_unique_word from being saved:</h2>

      <ul>
      <% @lsa_training_unique_word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br />
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :category_frequency %><br />
    <%= f.number_field :category_frequency %>
  </div>
  <div class="field">
    <%= f.label :icf %><br />
    <%= f.text_field :icf %>
  </div>
  <div class="field">
    <%= f.label :lsa_document_id %><br />
    <%= f.number_field :lsa_document_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lsa_phd/app/views/lsa_training_unique_words/edit.html.erb
<h1>Editing lsa_training_unique_word</h1>

<%= render 'form' %>

<%= link_to 'Show', @lsa_training_unique_word %> |
<%= link_to 'Back', lsa_training_unique_words_path %>

lsa_phd/app/views/lsa_training_unique_words/index.html.erb
<h1>Listing lsa_training_unique_words</h1>
<a href="/lsa_documents">Back</a>
<br/><br/>
<table>
  <tr>
    <th>Word</th>
    <th>Category frequency</th>
    <th></th>
    <th>Icf</th>
    <th></th>
    <th>Lsa document</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lsa_training_unique_words.each do |lsa_training_unique_word| %>
  <tr>
    <td><%= lsa_training_unique_word.word %></td>
    <td><%= lsa_training_unique_word.category_frequency %></td>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td><%= lsa_training_unique_word.icf %></td>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td><%= lsa_training_unique_word.lsa_document_id %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lsa training unique word', new_lsa_training_unique_word_path %>

lsa_phd/app/views/lsa_training_unique_words/new.html.erb
<h1>New lsa_training_unique_word</h1>

<%= render 'form' %>

<%= link_to 'Back', lsa_training_unique_words_path %>

lsa_phd/app/views/lsa_training_unique_words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Word:</b>
  <%= @lsa_training_unique_word.word %>
</p>

<p>
  <b>Category frequency:</b>
  <%= @lsa_training_unique_word.category_frequency %>
</p>

<p>
  <b>Icf:</b>
  <%= @lsa_training_unique_word.icf %>
</p>

<p>
  <b>Lsa document:</b>
  <%= @lsa_training_unique_word.lsa_document_id %>
</p>


<%= link_to 'Edit', edit_lsa_training_unique_word_path(@lsa_training_unique_word) %> |
<%= link_to 'Back', lsa_training_unique_words_path %>