lsa_phd/config/routes.rb
Lsa::Application.routes.draw do

  resources :lsa_training_unique_words


  resources :flsa_results


  resources :lsa_test_words


  resources :lsa_test_sentences


  resources :lsa_words
  resources :lsa_sentences
  resources :lsa_documents
  resources :words
  resources :sentences
  resources :documents
  root to: 'documents#index'
  match ':controller(/:action(/:id))(.:format)'
end

lsa_phd/app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :content, :title, :label, :docno, :date
  has_many	:sentences, :dependent => :delete_all
  has_many	:words, :dependent => :delete_all
  has_many	:lsa_sentences, :dependent => :delete_all
  has_many	:lsa_test_sentences, :dependent => :delete_all
  has_many	:flsa_results, :dependent => :delete_all
end

lsa_phd/app/models/flsa_result.rb
class FlsaResult < ActiveRecord::Base
  attr_accessible :document_id, :f_measure, :flsa_label, :flsa_max_similarity, :label, :lsa_document_id, :lsa_label, :lsa_max_similarity, :precision, :recall
  belongs_to :lsa_document
  belongs_to :document
end

lsa_phd/app/models/lsa_document.rb
class LsaDocument < ActiveRecord::Base
  attr_accessible :title, :matrix, :testing, :training
  has_many	:lsa_sentences, :dependent => :delete_all
  has_many	:lsa_test_sentences, :dependent => :delete_all
  has_many	:lsa_words, :dependent => :delete_all
  has_many	:lsa_test_words, :dependent => :delete_all
  has_many	:flsa_results, :dependent => :delete_all
  has_many	:lsa_training_unique_words, :dependent => :delete_all
end

lsa_phd/app/models/lsa_sentence.rb
class LsaSentence < ActiveRecord::Base
  attr_accessible :lsa_document_id, :sentence, :document_id
  has_many	:lsa_words, :dependent => :delete_all
  belongs_to :lsa_document
  belongs_to :document
end

lsa_phd/app/models/lsa_test_sentence.rb
class LsaTestSentence < ActiveRecord::Base
  attr_accessible :document_id, :f_measure, :label, :lsa_document_id, :lsa_label, :precision, :recall, :sentence, :similarity
  has_many	:lsa_test_words, :dependent => :delete_all
  belongs_to :lsa_document
  belongs_to :document
end

lsa_phd/app/models/lsa_test_word.rb
class LsaTestWord < ActiveRecord::Base
  attr_accessible :lsa_document_id, :lsa_test_sentence_id, :word
  belongs_to	:lsa_test_sentence
  belongs_to	:lsa_document
end

lsa_phd/app/models/lsa_training_unique_word.rb
class LsaTrainingUniqueWord < ActiveRecord::Base
  attr_accessible :category_frequency, :icf, :lsa_document_id, :word, :occurrence
  belongs_to :lsa_document
end

lsa_phd/app/models/lsa_word.rb
class LsaWord < ActiveRecord::Base
  attr_accessible :lsa_document_id, :lsa_sentence_id, :word
  belongs_to	:lsa_sentence
  belongs_to	:lsa_document
end

lsa_phd/app/models/sentence.rb
class Sentence < ActiveRecord::Base
  attr_accessible :document_id, :sentence
  has_many	:words, :dependent => :delete_all
  belongs_to :document
end

lsa_phd/app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :document_id, :sentence_id, :word, :corpus
  belongs_to	:sentence
  belongs_to	:document
end

lsa_phd/app/controllers/lsa_test_sentences_controller.rb
class LsaTestSentencesController < ApplicationController
  # GET /lsa_test_sentences
  # GET /lsa_test_sentences.json
  def index
    @lsa_test_sentences = LsaTestSentence.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lsa_test_sentences }
    end
  end

  # GET /lsa_test_sentences/1
  # GET /lsa_test_sentences/1.json
  def show
    @lsa_test_sentence = LsaTestSentence.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lsa_test_sentence }
    end
  end

  # GET /lsa_test_sentences/new
  # GET /lsa_test_sentences/new.json
  def new
    @lsa_test_sentence = LsaTestSentence.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lsa_test_sentence }
    end
  end

  # GET /lsa_test_sentences/1/edit
  def edit
    @lsa_test_sentence = LsaTestSentence.find(params[:id])
  end

  # POST /lsa_test_sentences
  # POST /lsa_test_sentences.json
  def create
    @lsa_test_sentence = LsaTestSentence.new(params[:lsa_test_sentence])

    respond_to do |format|
      if @lsa_test_sentence.save
        format.html { redirect_to @lsa_test_sentence, notice: 'Lsa test sentence was successfully created.' }
        format.json { render json: @lsa_test_sentence, status: :created, location: @lsa_test_sentence }
      else
        format.html { render action: "new" }
        format.json { render json: @lsa_test_sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lsa_test_sentences/1
  # PUT /lsa_test_sentences/1.json
  def update
    @lsa_test_sentence = LsaTestSentence.find(params[:id])

    respond_to do |format|
      if @lsa_test_sentence.update_attributes(params[:lsa_test_sentence])
        format.html { redirect_to @lsa_test_sentence, notice: 'Lsa test sentence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lsa_test_sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lsa_test_sentences/1
  # DELETE /lsa_test_sentences/1.json
  def destroy
    @lsa_test_sentence = LsaTestSentence.find(params[:id])
    @lsa_test_sentence.destroy

    respond_to do |format|
      format.html { redirect_to lsa_test_sentences_url }
      format.json { head :no_content }
    end
  end
end

lsa_phd/app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.json
  def index
    @words = Word.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/new
  # GET /words/new.json
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to words_url, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
end

lsa_phd/app/helpers/application_helper.rb
module ApplicationHelper
end

lsa_phd/app/helpers/documents_helper.rb
module DocumentsHelper
end

lsa_phd/app/helpers/flsa_results_helper.rb
module FlsaResultsHelper
end

lsa_phd/app/helpers/lsa_documents_helper.rb
module LsaDocumentsHelper
end

lsa_phd/app/helpers/lsa_sentences_helper.rb
module LsaSentencesHelper
end

lsa_phd/app/helpers/lsa_test_sentences_helper.rb
module LsaTestSentencesHelper
end

lsa_phd/app/helpers/lsa_test_words_helper.rb
module LsaTestWordsHelper
end

lsa_phd/app/helpers/lsa_words_helper.rb
module LsaWordsHelper
end

lsa_phd/app/helpers/sentences_helper.rb
module SentencesHelper
end

lsa_phd/app/helpers/words_helper.rb
module WordsHelper
end

lsa_phd/app/views/lsa_test_sentences/_form.html.erb
<%= form_for(@lsa_test_sentence) do |f| %>
  <% if @lsa_test_sentence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lsa_test_sentence.errors.count, "error") %> prohibited this lsa_test_sentence from being saved:</h2>

      <ul>
      <% @lsa_test_sentence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lsa_document_id %><br />
    <%= f.number_field :lsa_document_id %>
  </div>
  <div class="field">
    <%= f.label :document_id %><br />
    <%= f.number_field :document_id %>
  </div>
  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :lsa_label %><br />
    <%= f.text_field :lsa_label %>
  </div>
  <div class="field">
    <%= f.label :precision %><br />
    <%= f.text_field :precision %>
  </div>
  <div class="field">
    <%= f.label :recall %><br />
    <%= f.text_field :recall %>
  </div>
  <div class="field">
    <%= f.label :f_measure %><br />
    <%= f.text_field :f_measure %>
  </div>
  <div class="field">
    <%= f.label :similarity %><br />
    <%= f.text_area :similarity %>
  </div>
  <div class="field">
    <%= f.label :sentence %><br />
    <%= f.text_area :sentence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lsa_phd/app/views/lsa_test_sentences/edit.html.erb
<h1>Editing lsa_test_sentence</h1>

<%= render 'form' %>

<%= link_to 'Show', @lsa_test_sentence %> |
<%= link_to 'Back', lsa_test_sentences_path %>

lsa_phd/app/views/lsa_test_sentences/index.html.erb
<h1>Listing lsa_test_sentences</h1>

<table>
  <tr>
    <th>Lsa document</th>
    <th>Document</th>
    <th>Label</th>
    <th>Lsa label</th>
    <th>Precision</th>
    <th>Recall</th>
    <th>F measure</th>
    <th>Similarity</th>
    <th>Sentence</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lsa_test_sentences.each do |lsa_test_sentence| %>
  <tr>
    <td><%= lsa_test_sentence.lsa_document_id %></td>
    <td><%= lsa_test_sentence.document_id %></td>
    <td><%= lsa_test_sentence.label %></td>
    <td><%= lsa_test_sentence.lsa_label %></td>
    <td><%= lsa_test_sentence.precision %></td>
    <td><%= lsa_test_sentence.recall %></td>
    <td><%= lsa_test_sentence.f_measure %></td>
    <td><%= lsa_test_sentence.similarity %></td>
    <td><%= lsa_test_sentence.sentence %></td>
    <td><%= link_to 'Show', lsa_test_sentence %></td>
    <td><%= link_to 'Edit', edit_lsa_test_sentence_path(lsa_test_sentence) %></td>
    <td><%= link_to 'Destroy', lsa_test_sentence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lsa test sentence', new_lsa_test_sentence_path %>

lsa_phd/app/views/lsa_test_sentences/new.html.erb
<h1>New lsa_test_sentence</h1>

<%= render 'form' %>

<%= link_to 'Back', lsa_test_sentences_path %>

lsa_phd/app/views/lsa_test_sentences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lsa document:</b>
  <%= @lsa_test_sentence.lsa_document_id %>
</p>

<p>
  <b>Document:</b>
  <%= @lsa_test_sentence.document_id %>
</p>

<p>
  <b>Label:</b>
  <%= @lsa_test_sentence.label %>
</p>

<p>
  <b>Lsa label:</b>
  <%= @lsa_test_sentence.lsa_label %>
</p>

<p>
  <b>Precision:</b>
  <%= @lsa_test_sentence.precision %>
</p>

<p>
  <b>Recall:</b>
  <%= @lsa_test_sentence.recall %>
</p>

<p>
  <b>F measure:</b>
  <%= @lsa_test_sentence.f_measure %>
</p>

<p>
  <b>Similarity:</b>
  <%= @lsa_test_sentence.similarity %>
</p>

<p>
  <b>Sentence:</b>
  <%= @lsa_test_sentence.sentence %>
</p>


<%= link_to 'Edit', edit_lsa_test_sentence_path(@lsa_test_sentence) %> |
<%= link_to 'Back', lsa_test_sentences_path %>