lsa_phd/config/routes.rb
Lsa::Application.routes.draw do

  resources :lsa_training_unique_words


  resources :flsa_results


  resources :lsa_test_words


  resources :lsa_test_sentences


  resources :lsa_words
  resources :lsa_sentences
  resources :lsa_documents
  resources :words
  resources :sentences
  resources :documents
  root to: 'documents#index'
  match ':controller(/:action(/:id))(.:format)'
end

lsa_phd/app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :content, :title, :label, :docno, :date
  has_many	:sentences, :dependent => :delete_all
  has_many	:words, :dependent => :delete_all
  has_many	:lsa_sentences, :dependent => :delete_all
  has_many	:lsa_test_sentences, :dependent => :delete_all
  has_many	:flsa_results, :dependent => :delete_all
end

lsa_phd/app/helpers/documents_helper.rb
module DocumentsHelper
end

lsa_phd/app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= f.label :date %><br />
    <%#= f.text_field :date, :size => "20" %>
  </div>
  <div class="field">
    <%#= f.label :title %><br />
    <%#= f.text_field :title, :size => "60" %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :size => "100x20"%>
  </div>
  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label, :size => "40" %>
  </div>
  <div class="field">
    <%#= f.label :docno %><br />
    <%#= f.text_field :docno, :size => "10" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<br/>
<% end %>

lsa_phd/app/views/documents/create_sentences.erb
<h1>Sentences <%= @sentences.count %></h1>
<table>
  <tr>
    <th>Sl.No</th>
    <th>Sentence</th>
    <th>Document</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% i = 1 %>
<% @sentences.each do |sentence| %>
  <tr>
    <td><%= i %></td>
    <td><%= sentence.sentence %></td>
    <td><%= sentence.document_id %></td>
    <td><a href="/documents/words_in_sentence/<%= sentence.id %>">Words</a></td>
    <td><%= link_to 'Edit', edit_sentence_path(sentence) %></td>
    <td><%= link_to 'Delete', sentence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% i = i + 1 %>
<% end %>
</table>
<br />
<a href="/documents">Back</a>

lsa_phd/app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

lsa_phd/app/views/documents/gong_liu_summary.erb
<h2>V transpose matrix</h2>
<table border="1">
	<tr><td></td>
	<% for j in 1..@d.sentences.count %>
		<td>Sen <%= j %></td>
	<% end %>
	</tr>
	<% for i in 0..@dimensions - 1 %>
	<tr>
		<td>Con <%= i + 1 %></td>
		<% for j in 0..@d.sentences.count - 1 %>
			<% if j == @row_greatest[i] %>
				<td style="background-color: yellow;"><%= @vt[i,j].round(3) %></td>
			<% else %>
				<td><%= @vt[i,j].round(3) %></td>
			<% end %>
		<% end %>
	</tr>
	<% end %>
</table>
<br/>
<h2>Extractive summary</h2>
Title: <%= @d.title %><br/>
<% for k in 0..@sentences.count - 1 %>
	<%= k + 1 %> 
	<% if @row_greatest.include? k %>
		<label style="background-color: yellow;"><%= @sentences[k] %>. </label>
	<% else %>
		<label><%= @sentences[k] %>. </label>
	<% end %>
	<br/>
<% end %>
<br/>
<a href="/documents">Back</a>

lsa_phd/app/views/documents/index.html.erb
<h1>Documents <%= @documents.count %></h1>
<!-- <a href="/documents/seperate_by_space/1">Create Content</a> -->
<%= link_to 'New Document', new_document_path %>
<!-- <a href="/documents/create_sentences/1">Create Sentences</a> |  -->
<!-- <a href="/documents/create_words/1">Create Words</a> | -->
<!-- <a href="/documents/tf_matrix/1">Create Matrix</a><br/><br/> -->
<!-- <a href="/lsa_documents/create_summary_train_set/1?round=CSLSA_20&d1=1&d2=2">CSLSA_20</a> |
<a href="/lsa_documents/create_summary_train_set/1?round=CSLSA_60&d1=1&d2=2">CSLSA_60</a> |
<a href="/lsa_documents/create_summary_train_set/1?round=CSLSA_50&d1=1&d2=2">CSLSA_50</a> |
<a href="/lsa_documents/create_summary_train_set/1?round=CSLSA_40&d1=1&d2=2">CSLSA_40</a> |
<a href="/lsa_documents/create_summary_train_set/1?round=CSLSA_30&d1=1&d2=2">CSLSA_30</a> | -->
<!-- <a href="/lsa_documents/create_dataset/1?round=CSLSA&d1=1&d2=2">CSLSA</a> | -->
<!-- <a href="/lsa_documents/create_summary_train_set/1?round=DSLSA_20&d1=1&d2=2">DSLSA_20</a> |
<a href="/lsa_documents/create_summary_train_set/1?round=DSLSA_30&d1=1&d2=2">DSLSA_30</a> |
<a href="/lsa_documents/create_summary_train_set/1?round=DSLSA_40&d1=1&d2=2">DSLSA_40</a> |
<a href="/lsa_documents/create_summary_train_set/1?round=DSLSA_50&d1=1&d2=2">DSLSA_50</a> |
<a href="/lsa_documents/create_summary_train_set/1?round=DSLSA_60&d1=1&d2=2">DSLSA_60</a> | -->
<br/><br/>
<!-- <a href="/lsa_documents">View Rounds</a> -->
<br/><br/>
<table>
<% @documents.each do |document| %>
<tr>
  <tr><td>TITLE: <%= document.title %></td></tr>
  <tr><td>CONTENT: <%= document.content %></td></tr>
  <tr><td>DATE: <%= document.date %></td></tr>
  <tr><td>LABEL: <%= document.label %></td></tr>
  <tr><td>DOCNO: <%= document.docno %></td></tr>
  <tr><td>ID: <%= document.id %></td></tr>
  <tr><td>
       <!-- <a href="/documents/matrix/<%= document.id %>">TF Matrix</a> | -->
<!--  | <a href="/documents/augmented_tf_matrix/<%= document.id %>">Augmented TF</a>
      | <a href="/documents/idf_matrix/<%= document.id %>">IDF</a>
      | <a href="/documents/tfidf_matrix/<%= document.id %>">TFIDF</a>
      | <a href="/documents/boolean_matrix/<%= document.id %>">Boolean</a>
      | <a href="/documents/log_matrix/<%= document.id %>">Log</a>       -->
      <a href="/documents/sentences/<%= document.id %>">Sentences</a>
      | <a href="/documents/words/<%= document.id %>">Words</a>
      <!-- | <a href="/documents/gong_liu_summary/<%= document.id %>">Extract</a> -->
<!--       | <a href="/documents/steinberger_summary/<%= document.id %>">Steinberger</a>
      | <a href="/documents/ozsoy_cross/<%= document.id %>">Ozsoy_Cross</a>
      | <a href="/documents/ozsoy_topic/<%= document.id %>">Ozsoy_Topic</a> -->
      <!-- | <a href="/documents/lsi/<%= document.id %>">LSI</a> -->
      | <a href="/documents/edit/<%= document.id %>" target="_blank">Edit</a> 
      | <%= link_to 'Delete', document, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
  </tr>
  <tr><td><br/></td></tr>
</tr>
<% end %>
</table>

lsa_phd/app/views/documents/lsi.erb
<h2>Sentence to Sentence similarity: <%= @sen_sen.rows.count %> x <%= @sen_sen.columns.count %></h2>
<table border="1">
	<tr><td></td>
		<% for j in 1..(@sen_sen.columns.count) %>
			<td><b><%= j %></b></td>
		<% end %>
	</tr>
	<% for i in 0..(@sen_sen.rows.count - 1) %>
  <tr>
  	<td><b><%= i + 1 %></b></td>
      <% for j in 0..(@sen_sen.columns.count - 1) %>
      	<td>
      		<%= @sen_sen[i,j].round(3) %>
      	</td>
      <% end %>
  </tr>
  <% end %>
</table>
<br/>

<h2>Word to Word similarity: <%= @word_word.rows.count %> x <%= @word_word.columns.count %></h2>
<table border="1">
  <tr><td></td>
    <% for j in 1..(@word_word.columns.count) %>
      <td><b><%= j %></b></td>
    <% end %>
  </tr>
  <% for i in 0..(@word_word.rows.count - 1) %>
  <tr>
    <td><b><%= i + 1 %></b></td>
      <% for j in 0..(@word_word.columns.count - 1) %>
        <td>
          <%= @word_word[i,j].round(3) %>
        </td>
      <% end %>
  </tr>
  <% end %>
</table>
<br/>

<h2>LSI matrix Ak: <%= @ak.rows.count %> x <%= @ak.columns.count %></h2>
<table border="1">
  <tr><td></td>
    <% for j in 1..(@ak.columns.count) %>
      <td>Sen <%= j %></td>
    <% end %>
  </tr>
  <% for i in 0..(@ak.rows.count - 1) %>
  <tr>
    <td><%= @words[i] %></td>
      <% for j in 0..(@ak.columns.count - 1) %>
        <td><%= @ak[i,j].round(3) %></td>
      <% end %>     
    </tr>
  <% end %>
</table>
<br/>

<h2>Term by Concept matrix Uk: <%= @uk.rows.count %> x <%= @uk.columns.count %></h2>
<table border="1">
  <tr><td></td>
    <% for j in 1..(@uk.columns.count) %>
      <td>Con <%= j %></td>
    <% end %>
  </tr>
  <% for i in 0..(@uk.rows.count - 1) %>
  <tr>
    <td><%= @words[i] %></td>
      <% for j in 0..(@uk.columns.count - 1) %>
        <td><%= @uk[i,j].round(3) %></td>
      <% end %>     
    </tr>
  <% end %>
</table>
<br/>

<h2>Concept by Concept matrix Sk: <%= @sk.rows.count %> x <%= @sk.columns.count %></h2>
<table border="1">
  <tr><td></td>
    <% for j in 1..(@sk.columns.count) %>
      <td>Con <%= j %></td>
    <% end %>
  </tr>
  <% for i in 0..(@sk.rows.count - 1) %>
  <tr>
    <td>Con <%= i + 1 %></td>
      <% for j in 0..(@sk.columns.count - 1) %>
        <td><%= @sk[i,j].round(3) %></td>
      <% end %>     
    </tr>
  <% end %>
</table>
<br/>

<h2>Concept by Sentence matrix Vk transpose: <%= @vkt.rows.count %> x <%= @vkt.columns.count %></h2>
<table border="1">
  <tr><td></td>
    <% for j in 1..(@vkt.columns.count) %>
      <td>Sen <%= j %></td>
    <% end %>
  </tr>
  <% for i in 0..(@vkt.rows.count - 1) %>
  <tr>
    <td>Con <%= i + 1 %></td>
      <% for j in 0..(@vkt.columns.count - 1) %>
        <td><%= @vkt[i,j].round(3) %></td>
      <% end %>     
    </tr>
  <% end %>
</table>
<br/>

lsa_phd/app/views/documents/matrix.erb
<h2>Term by Sentence matrix: <%= @all_words.count %> x <%= @d.sentences.count %></h2>
<a href="/documents/lsi/<%= @d.id %>">LSI</a> | <a href="/documents">Back</a>
<br/><br/>
<table border="1">
	<tr><td></td>
		<% for j in 1..@d.sentences.count %>
			<td><b><%= j %></b></td>
		<% end %>
	</tr>
	<% i = 0 %>
	<% @dmatrix.each do |dm| %>
		<% row = dm.split(",").collect{ |s| s.to_f } %>
		<tr>
		    <td><b><%= @all_words[i] %></b></td>
		    <% row.each do |r| %>
				<td align="right"><%= r %></td>
			<% end %>
		</tr>
		<% i = i + 1 %>
	<% end %>
</table>
<br/>

lsa_phd/app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

lsa_phd/app/views/documents/ozsoy_cross.erb
<h2>V transpose matrix</h2>
<table border="1">
	<tr><td></td>
	<% for j in 1..@d.sentences.count %>
		<td>Sen <%= j %></td>
	<% end %>
	</tr>
	<% for i in 0..9 %>
	<tr>
		<td>Con <%= i + 1 %></td>
		<% for j in 0..@d.sentences.count - 1 %>
			<td><%= @vt[i,j].round(3) %></td>
		<% end %>
	</tr>
	<% end %>
	<tr><td>Length</td>
		<% for i in 0..@d.sentences.count - 1 %>
		  <% if i == @position %>
			<td style="background-color: yellow;"><%= @sentence_length[i] %></td>
		  <% else %>
			<td><%= @sentence_length[i] %></td>
		  <% end %>
		<% end %>
	</tr>
</table>
<br/>
<h2>Extractive summary</h2>
Title: <%= @d.title %><br/>
<% for k in 0..@sentences.count - 1 %>
	<%= k + 1 %> 
	<% if k == @position %>
		<label style="background-color: yellow;"><%= @sentences[k] %>. </label>
	<% else %>
		<label><%= @sentences[k] %>. </label>
    <% end %>
	<br/>
<% end %>
<br/>
<a href="/documents">Back</a>

lsa_phd/app/views/documents/sentences.erb
<h1>Sentences <%= @d.sentences.count %></h1>
<table>
  <tr>
    <th>Sl.No</th>
    <th>Sentence</th>
    <th>Document</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% i = 1 %>
<% @d.sentences.each do |sentence| %>
  <tr>
    <td><%= i %></td>
    <td><%= sentence.sentence %></td>
    <td><%= sentence.document_id %></td>
    <td><a href="/documents/words_in_sentence/<%= sentence.id %>">Words</a></td>
    <td><%= link_to 'Edit', edit_sentence_path(sentence) %></td>
    <td><%= link_to 'Delete', sentence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% i = i + 1 %>
<% end %>
</table>
<br />
<a href="/documents">Back</a>
<%#= link_to 'New Document', new_document_path %>

lsa_phd/app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @document.title %>
</p>

<p>
  <b>Content:</b>
  <%= @document.content %>
</p>

<p>
  <b>Label:</b>
  <%= @document.label %>
</p>

<p>
  <b>Docno:</b>
  <%= @document.docno %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

lsa_phd/app/views/documents/steinberger_summary.erb
<h2>V matrix</h2>
<table border="1">
	<tr><td></td>
	<% for j in 1..@d.sentences.count %>
		<td>Con <%= j %></td>
	<% end %>
		<td>Length</td>
	</tr>
	<% for i in 0..@sentences.count - 1 %>
	<tr>
		<td>Sen <%= i + 1 %></td>
		<% for j in 0..@d.sentences.count - 1 %>
			<td><%= @v[i,j].round(3) %></td>
		<% end %>
		<% if i == @position %>
			<td style="background-color: yellow;"><%= @length[i] %></td>
		<% else %>
			<td><%= @length[i] %></td>
		<% end %>
	</tr>
	<% end %>
</table>
<br/>
<h2>Extractive summary</h2>
Title: <%= @d.title %><br/>
<% for k in 0..@sentences.count - 1 %>
	<%= k + 1 %> 
	<% if k == @position %>
		<label style="background-color: yellow;"><%= @sentences[k] %>. </label>
	<% else %>
		<label><%= @sentences[k] %>. </label>
    <% end %>
	<br/>
<% end %>
<br/>
<a href="/documents">Back</a>

lsa_phd/app/views/documents/words.erb
<h1>Words <%= @d.words.count %></h1>
<table>
  <tr>
    <th>Word</th>
    <th>Sentence</th>
    <th>Document</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @d.words.each do |word| %>
  <tr>
    <td><%= word.word %></td>
    <td><%= word.sentence_id %></td>
    <td><%= word.document_id %></td>
    <!-- <td><%#= link_to 'Show', word %></td> -->
    <!-- <td><%#= link_to 'Edit', edit_word_path(word) %></td> -->
    <td><%= link_to 'Delete', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />
<a href="/documents">Back</a>

lsa_phd/app/views/documents/words_in_sentence.erb
<h1>Words <%= @s.words.count %></h1>
<table>
  <tr>
    <th>Word</th>
    <th>Sentence</th>
    <th>Document</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @s.words.each do |word| %>
  <tr>
    <td><%= word.word %></td>
    <td><%= word.sentence_id %></td>
    <td><%= word.document_id %></td>
    <td><%= link_to 'Show', word %></td>
    <td><%= link_to 'Edit', edit_word_path(word) %></td>
    <td><%= link_to 'Delete', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />
<a href="/documents/sentences/<%= @s.document_id %>">Back</a>